flaskresponse/filter/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flaskresponse.filter.forms import FilterForm, SortingForm
import requests
from flask_login import login_user, current_user, logout_user, login_required 
from flaskresponse.filter.utils import dump_data, retrieve_data, retrieve_results, clear_results_file
from flaskresponse.filter.scrape import cleanhtml, get_question_answers_comments, print_answers_comments, get_accepted_answer_comments
import re
from bs4 import BeautifulSoup
import pickle
import pandas as pd
import tensorflow as tf


filter_blueprint = Blueprint('filter_blueprint', __name__)

@filter_blueprint.route("/report")
@login_required
def report():
	data = retrieve_data()
	results = retrieve_results()
	results_asc = results[0]
	results_desc = results[1]
	return render_template('report.html', title='Report', result=results_desc)


@filter_blueprint.route("/filter", methods=['GET','POST'])
@login_required
def filter():
	form = FilterForm()
	if form.validate_on_submit():
		if form.submit_url.data:
			page = requests.get(form.url.data)
			soup = BeautifulSoup(page.content, 'html.parser')
			question, answers, comments, answers_user, comments_user = get_question_answers_comments(soup)
			accepted_answer, accepted_comments = get_accepted_answer_comments(soup)
			dump_data(question,answers,comments,accepted_answer,accepted_comments, answers_user, comments_user)
			flash('Question, answers and comments from the specified URL are successfully extracted','success')
			data = retrieve_data()
			return render_template('before_filter_display.html', title='Data', question = data[0], answers = data[1],comments = data[2], accepted_answer = data[3], accepted_comments = data[4], answers_user = data[5], comments_user = data[6])
		if form.submit_filter.data:
			print('Start')
			import flaskresponse.filter.level1 as f1
			f1.filter_level1()
			print('After level 1')
			import flaskresponse.filter.level2 as f2
			f2.filter_level2()
			print('After level 2')
			results = retrieve_results()
			results_asc = results[0]
			results_desc = results[1]
			form = SortingForm()
			return render_template('filter_results.html', form=form, title='Results',result = results_desc, minimum = 0, maximum = 100)
	return render_template('url.html',title='Upload',form=form,legend ='Enter URL')


@filter_blueprint.route("/before_filter_display")
@login_required
def before_filter_display():
	data = retrieve_data()
	return render_template('before_filter_display.html', title='Data', question = data[0], answers = data[1],comments = data[2], accepted_answer = data[3], accepted_comments = data[4], answers_user = data[5], comments_user = data[6])


@filter_blueprint.route("/filter_results",methods=['GET', 'POST'])
@login_required
def filter_results():
	form = SortingForm()
	results = retrieve_results()
	results_asc = results[0]
	results_desc = results[1]
	if form.validate_on_submit():
		minimum = float(form.minimum.data)
		maximum = float(form.maximum.data)
		if form.htl.data:
			return render_template('filter_results.html', form=form, title='Results', result=results_desc, minimum = minimum, maximum = maximum)
		if form.lth.data:
			return render_template('filter_results.html', form=form, title='Results', result=results_asc, minimum = minimum, maximum = maximum)	
	return render_template('filter_results.html', form=form, title='Results', result=results_desc, minimum = 0, maximum = 100)

flaskresponse/main/routes.py
from flask import render_template, Blueprint, url_for

main = Blueprint('main', __name__)

@main.route("/home") # routes for home page
def home():
	img = url_for('static',filename='images/home_bg.jpg')
	return render_template('home.html',img=img) # render template is used to display the page to be displayed when the route is called. posts is passed and displayed on home page using Jinja templating
    

@main.route("/about")
def about():
    return render_template('about.html',title='about') # title is set as About. Wherever know title is passed, default title is used

flaskresponse/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, session
from flaskresponse import db, bcrypt 
from flaskresponse.models import User
from flaskresponse.users.forms import RegistrationForm, LoginForm, UpdateAccountForm
from flask_login import login_user, current_user, logout_user, login_required 
from flaskresponse.users.utils import save_picture
import requests

users = Blueprint('users', __name__)

@users.route("/register",methods=['GET','POST'])
def register(): 
	if current_user.is_authenticated: # is user is authenticated, redirect him to home
		return redirect(url_for('main.home'))
	form = RegistrationForm() # An object of the Registration form is created. 
	if form.validate_on_submit(): # If the user hits the submit button, the form is validated based on the default and custom validators in the forms.py Registration class. If there are no errors, the code block below is executed
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8') 
		user = User(username=form.username.data, email=form.email.data, password=hashed_password) # User info recieved from form is stored in User model from models.py
		db.session.add(user) # We use add method to add the user object filled with data into user(first letter lowercase of class User) table in sql alchemy db 
		db.session.commit() # We commit the changes to the database
		flash('Your account has been created! You are now able to log in','success') # flash message is displayed on login page and class is set as success to get a green message, which is done in layout.html
		return redirect(url_for('users.login')) # User is refirected to login page so that now they can login to the system
	return render_template('register.html',title='Register',form=form) # The form object is passed to the view and the components are displayed using jinja templating. If any errors are there, they are also displayed in the view (register.html)

@users.route("/",methods=['GET','POST'])
@users.route("/login",methods=['GET','POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first() # We check if the user with specified email is present 
		if user and bcrypt.check_password_hash(user.password, form.password.data): # If the user exists and the password matches with the password in db, user is authenticated
			login_user(user, remember=form.remember.data) # We accept yes/no from rememeber me boolean field
			next_page = request.args.get('next') # next arguement from the url is used to redirect the user to desired page if he directly tried to access a page via url 
			return redirect(next_page) if next_page else redirect(url_for('filter_blueprint.filter')) # We redirect the user to home page after successful login
		else:
			flash('Login Unsuccessful. Please check username and password','danger') # If user is not authenticated, we display a flash message with class='danger' which is set in the layout.html
	return render_template('login.html',title='Login',form=form) 

@users.route("/logout")
def logout():
	logout_user() # logs out the user from login_manager system
	return redirect(url_for('users.login')) # User is redirected to home after logout


@users.route("/account",methods=['GET','POST']) 
@login_required # This page is accessible if the user is logged in
def account():
	form = UpdateAccountForm() # Instance of form
	if form.validate_on_submit():
		if form.picture.data:
			picture_file = save_picture(form.picture.data) # if new image is uploaded, it is stored in the database
			current_user.image_file = picture_file # the image file uploaded is direclty stored in current_user and the data is automatically synched with sql database after commit
		current_user.username = form.username.data # new username is stored
		current_user.email = form.email.data # new email is stored
		db.session.commit() # commit updates the values changed in current_user in the database
		flash('Your account has been updated','success') # A message is flashed suggesting that updates where successful
		return redirect(url_for('users.account')) # post get redirect (avoid data will be resubmitted message)
	elif request.method == 'GET': # (Pre populating the fields)If the page is accessed in general, the original username and email are displayed.
		form.username.data = current_user.username
		form.email.data = current_user.email
	image_file = url_for('static',filename='profile_pics/'+current_user.image_file) # image file is also passed to the view (account.html)
	return render_template('account.html',title='Account',image_file=image_file, form=form) # (Populating the form in view)render the view and display error messages, if any

flaskresponse/templates/about.html
{% extends 'layout.html' %}
{% block content %}

{% endblock content %}

flaskresponse/templates/account.html
{% extends 'layout.html' %}
{% block content %}
	<div class="content-section">
	  <div class="media">
	    <img class="rounded-circle account-img" src="{{ image_file }}">
	    <div class="media-body">
	      <h2 class="account-heading">{{ current_user.username }}</h2>
	      <p class="text-secondary">{{ current_user.email }}</p>
	    </div>
	  </div>
	  
	  <form method="POST" action="" novalidate enctype="multipart/form-data"> <!-- enctype for file upload -->
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Account Info</legend>
				<div class="form-group">
					{{ form.username.label(class="form-control-label") }}
					{% if form.username.errors %}
						{{form.username(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.username.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.username(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					{% if form.email.errors %}
						{{form.email(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.picture.label() }}
					{{ form.picture(class = "form-control-file") }}
					{% if form.picture.errors %}
						{% for error in form.picture.errors %}
							<span class = "text-danger">{{ error }}</span>
						{% endfor %}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>

	</div>
{% endblock content %}

flaskresponse/templates/before_filter_display.html
{% extends 'layout.html' %}
{% block content %}


<h1>
	{{ question }}
</h1>

		
<h4>Model Answer</h4>
		<article class="media content-section">
		  <div class="media-body">
		    <div class="article-metadata">
		      <h6><a class="article-title">{{ accepted_answer }}</a></h6>
		      <!--
		      {% if accepted_comments is not string and accepted_comments|length > 0 %}
		      	{% for comm in accepted_comments %}
		      		<article class="media content-section" style = "margin-left:15%;background-color: #5f788a;color:#ffffff">
		      			<p>{{ comm }}</p>
		      		</article>
		      	{% endfor %}
		      {% else %}
		      	<p></p>
		      {% endif %}
		  -->
		    </div>
		  </div>
		</article>

<h4>Answers</h4>
	{% for ans in answers %}
		<article class="media content-section">
		  <div class="media-body">
		    <div class="article-metadata">
		    <span class="badge badge-secondary" style="color:#ffffff">{{answers_user[loop.index0]}}</span>
		    		<h6><a class="article-title">{{ans}}</a></h6>		      
		      	{% if comments[loop.index0] is not string and comments[loop.index0] is iterable %}
		     		{% for comm,user in zip(comments[loop.index0],comments_user[loop.index0]) %}
		     			<article class="media content-section" style = "margin-left:15%;background-color: #5f788a;color:#ffffff">
		     					<span class="badge badge-secondary" style="color:#ffffff">{{user}}</span>
		      					<p>{{ comm }}</p>
		      			</article>
		      		{% endfor %}
		      	{% endif %}	
		    </div>
		  </div>
		</article>
	{% endfor %}

{% endblock content %}

flaskresponse/templates/create_post.html
{% extends 'layout.html' %}
{% block content %}
	<div class='content-section'>
		<form method="POST" action="" novalidate>
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">{{ legend }}</legend>
				<div class="form-group">
					{{ form.title.label(class="form-control-label") }}
					{% if form.title.errors %}
						{{form.title(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.title.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.title(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.content.label(class="form-control-label") }}
					{% if form.content.errors %}
						{{form.content(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.content.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.content(class="form-control form-control-lg") }}
					{% endif %}	
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
{% endblock content %}

flaskresponse/templates/filter_results.html
{% extends 'layout.html' %}
{% block content %}

<!-- 
0 - question
1 - accepted answer
2 - answers
que, accepted_answer, [ans_id, answer_user, answer, score, [comm_user, comm, score, pol]]
-->

<head>
	<script>
	function showFilter() {
	  var x = document.getElementById("filter");
	  if (x.style.display === "none") {
	    x.style.display = "block";
	  } else {
	    x.style.display = "none";
	  }
	}
</script>
</head>


<form method="POST" action="" novalidate>
{{ form.hidden_tag() }}

<h1>
	{{result[0]}}
</h1>
<input type="button" class = "btn btn-outline-info" onclick="showFilter()" value="Filter">

<div id="filter" style="display: none;">
	<br>
	<article class="media content-section">
		<div class="media-body">
		   	<div class="article-metadata">
				{{form.htl(class="btn btn-outline-info")}} {{form.lth(class="btn btn-outline-info")}}<br>
				<br><p>Enter the range (between 0 to 100):</p>
				{{form.minimum.label(class="form-control-label")}} : {{form.minimum(class="form-control form-control-lg") }}<br>
				{{form.maximum.label(class="form-control-label")}}  :  {{form.maximum(class="form-control form-control-lg") }}
			</div>
		</div>
	</article>	
</div>


<h4>Model Answer</h4>
		<article class="media content-section">
		  <div class="media-body">
		      <h6><a class="article-title">{{ result[1] }}</a></h6>
		  </div>
		</article>


	
	{% for res in result[2] %}
	{% if res[3]>=minimum and res[3]<=maximum %}
		<article class="media content-section">
			
		  <div class="media-body">
		    
		    	<span class="badge badge-secondary" style="color:#ffffff">{{res[1]}}</span>
		    	<span class="badge badge-secondary" style="float: right;">{{ res[3] }}</span>	 
		      <h6><a class="article-title">{{ res[2] }}</a></h6>	
		      <br><br>
		          	
		     		{% for comm in res[4] %}
		     		{% if comm[2]>=minimum and comm[2]<=maximum %}
		     			{% if comm[3] != -1 %}

		     			<article class="media content-section" style = "margin-left:15%;color:#ffffff;
		     				{% if comm[3]==1 %}
		     					background-color: green;
		     				{% else %}
		     					background-color: red;
		     				{% endif %}
		     			">	
		     			<div class="media-body">
		    				
									<span class="badge badge-secondary" style="color:white;">{{comm[0]}}</span>
		     						<span class="badge badge-secondary" style="float: right;">{{ comm[2] }}</span>	
		     						<p>{{ comm[1] }}</p>
				      		
				      	</div>		
		      			</article>
		      			{% endif %}
		      		{% endif %}
		      		{% endfor %}		  	  
		    
		  </div>
		</article>
	{% endif %}
	{% endfor %}
</form>
{% endblock content %}

flaskresponse/templates/home.html
<head>
	<style type="text/css">
body{
	position: relative;
}
	.bg {
	position: fixed;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    max-width: 100%;
    max-height: 100%;
    width: 100%;
    overflow: auto;
	}



	/* Centered text */
.left {
  position: absolute;
  top: 50%;
  font-size: 50px;
  font-weight: bold;
}

.container {
  position: relative;
  color: white;
}
	</style>
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="50">
{% extends 'layout.html' %}
{% block content %}

	<div id="section1">
		<img src="{{img}}" class="bg">
		<div class="container">
			<div class="left">
				Response Categorizer<br>
					<p style="font-size: 30px">			-An Automated Scoring System for Online Discussion Forums</p>
					<!--<article class="content-section" style="font-size: 25px;color:#5f788a">-->
					<ul style="font-size: 25px">
						<li> An automated system that scores the answers and comments on the post of your online discussion forum</li>
						<li> Fast processing is done to provide results in real time</li>
						<li> Filters can be applied for the evaluators to check out replies in different ranges</li>
						<li>The scored replies can alse be ordered in ascending and descending order</li>
						<li>Go To the filters tab to get started</li>
					</ul>
			</div>	
		</div>
	</div>

{% endblock content %}
</body>

flaskresponse/templates/layout.html
<!DOCTYPE html>
<html>
<head>
	 <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<style>
body {
  font-family: "Lato", sans-serif;
  transition: background-color .5s;
}

#openBtn{
	visibility: "hidden";
}

.sidenav {
  height: 100%;
  width: 200px;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}


.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 20px;
  display: block;
  color: white;
  transition: 0.3s;
}

.sidenav #a:hover {
  background-color: #ffffff;
  opacity: 0.5;
  color: #5f788a;
}


.sidenav p{
	font-size: 20px;
}

hr{
	width:90%;
	margin:0 auto;
	background-color: #ffffff;
}


.sidenav .closebtn {
  position: absolute;
  top: 0;
  right: 20px;
  font-size: 36px;
  margin-left: 50px;
}
{% if current_user.is_authenticated %} 
#main,#nav{
  transition: margin-left .5s;
  margin-left: 200px;
}
{% endif %}
@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}

#profile_pics{
	height: 15%;
	width: 80%;
}
	


</style>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

	{% if title %}
		<title>Response-{{ title }}</title>
	{% else %}
		<title>Response</title>
	{% endif %}
</head>

<body>
{% if current_user.is_authenticated %}
	<!-- Bootstrap CSS -->
	<div id="mySidenav" class="sidenav bg-dark" id="sidebar">
  		<a href="javascript:void(0)" style="color:white;" class="closebtn" onclick="closeNav()">&times;</a>
  		<img class="rounded-circle mx-auto d-block" id = "profile_pics" src="../static/profile_pics/{{current_user.image_file}}">
  		<h4 style="color:white;text-align:center">Dashboard</h4>
  		<hr><br>
  			<ul class="list-unstyled sidebar-body">
  				
  				<a style="color: #777;">Menu</a>
		    	<li> <a id="a" class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a></li>
		    	<!--
		     	<li><a id="a" class="nav-item nav-link"  href="{{ url_for('main.about') }}">About Us</a></li>-->
				<li><a id="a" class="nav-item nav-link"  href="{{ url_for('filter_blueprint.before_filter_display') }}">Data</a></li>
		    </ul><hr>
		    <ul class="list-unstyled sidebar-body">
		    	<a style="color: #777;">Filter</a>
		    	<li><a id="a" class="nav-item nav-link" href="{{ url_for('filter_blueprint.filter') }}">Filter</a></li>
		    	<li><a id="a" class="nav-item nav-link" href="{{ url_for('filter_blueprint.filter_results') }}">Results</a></li>
		        <li><a id="a" class="nav-item nav-link" href="{{ url_for('filter_blueprint.report') }}">Report</a></li>
		    </ul><hr>
		    <ul class="list-unstyled sidebar-body">	
		    	<a style="color: #777;">Account</a>     
		     	<li><a id="a" class="nav-item nav-link" href="{{ url_for('users.account') }}">Account Settings</a></li>
		     	<li><a id="a" class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a></li>
		    </ul>        
	</div>
{% endif %} 
`

	<header class="site-header">

		  <nav class="navbar navbar-expand-md bg-steel navbar-dark fixed-top" id="nav">
		  	{% if current_user.is_authenticated %}
		  		<span id="openBtn" style="font-size:30px;cursor:pointer;color:#ffffff" onclick="openNav()">&#9776;</span>
		  	{% endif %} 
		    <div class="container">

		      <a class="navbar-brand mr-4" href="/">Response Categorizer</a>
		      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
		        <span class="navbar-toggler-icon"></span>
		      </button>
		      <div class="collapse navbar-collapse" id="navbarToggle">
		        <div class="navbar-nav mr-auto">
		          {% if current_user.is_authenticated %}
		          	<a class="nav-item nav-link" href="{{ url_for('filter_blueprint.filter') }}">Filter</a>
		          	<a class="nav-item nav-link" href="{{ url_for('filter_blueprint.before_filter_display') }}">Data</a>
		      
		          	<a class="nav-item nav-link" href="{{ url_for('filter_blueprint.filter_results') }}">Results</a>
		          {% endif %}
		        </div>
		        <!-- Navbar Right Side -->
		        <div class="navbar-nav">
		        	{% if current_user.is_authenticated %}
		    		 <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
		        	{% else %}
		        		<a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
		          		<a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
		        	{% endif %}
		        </div>
		      </div>
		    </div>
		  </nav>
		</header>

<div id="main">
	<main role="main" class="container">
	  <div class="row">
	    <div class="col-md-8">
	      {% with messages = get_flashed_messages(with_categories=true) %}
	      		{% if messages %}
	      			{% for category,message in messages %}
	      				<div class="alert alert-{{ category }}">
	      					{{ message }}
	      				</div>
	      			{% endfor %}
	      		{% endif %}
	      {% endwith %}

		  {% block content %}{% endblock %}
		      
	    
	      
	    </div>
	  </div>
	</main>
</div>
	
		


	<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


	<!-- Sidenav -->
	<script>
		document.getElementById('main').addEventListener("click", function (evt) {
		    	document.getElementById("mySidenav").style.width = "0";
		  		document.getElementById("main").style.marginLeft= "0";
		  		document.getElementById("nav").style.marginLeft = "0";
		  	document.body.style.backgroundColor = "white";
		});

		function openNav() {
  			document.getElementById("mySidenav").style.width = "200px";
  			document.getElementById("main").style.marginLeft = "200px";
  			document.getElementById("nav").style.marginLeft = "200px";
  			document.getElementById("openBtn").style.visibility = "hidden";
		}

		function closeNav() {
		  document.getElementById("mySidenav").style.width = "0";
		  document.getElementById("main").style.marginLeft= "0";
		  document.getElementById("nav").style.marginLeft = "0";
		  document.getElementById("openBtn").style.visibility = "visible";
		  
		}
	</script>
            
  
</body>
</html>

flaskresponse/templates/login.html
{% extends 'layout.html' %}
{% block content %}
	<div class='content-section'>
		<form method="POST" action="" novalidate>
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Log In</legend>
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					{% if form.email.errors %}
						{{form.email(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}
					{% if form.password.errors %}
						{{form.password(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}	
				</div>
				<div class="form-check">
					{{ form.remember(class="form-check-input") }}
					{{ form.remember.label(class="form-check-label") }}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
			<small class="text-muted ml-2">
				<a href="#">Forgot Password?</a>
			</small>
		</form>
	</div>
	<div class="border-top pt-3">
		<small class="text-muted">
			Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
		</small>
	</div>
{% endblock content %}

flaskresponse/templates/upload.html
{% extends 'layout.html' %}
{% block content %}
	<div class='content-section'>
		<form method="POST" action="" novalidate enctype="multipart/form-data">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">{{ legend }}</legend>
				
				<div class="form-group">
					{{ form.csv1.label(class="form-control-label") }}
					{% if form.csv1.errors %}
						{{form.csv1(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.csv1.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.csv1(class="form-control form-control-lg") }}
					{% endif %}	
				</div>

				<div class="form-group">
					{{ form.csv2.label(class="form-control-label") }}
					{% if form.csv2.errors %}
						{{form.csv2(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.csv2.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.csv2(class="form-control form-control-lg") }}
					{% endif %}	
				</div>

				<div class="form-group">
					{{ form.csv3.label(class="form-control-label") }}
					{% if form.csv3.errors %}
						{{form.csv3(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.csv3.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.csv3(class="form-control form-control-lg") }}
					{% endif %}	
				</div>

			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
{% endblock content %}